### ISSUE TITLE
static list found empty

### ISSUE THREAD

**Issue by MitchvanWijngaarden** [hardy12994/ng4-auto-complete#3]
`  ngOnInit() {
    this.test()
}
`
`
test() {
   let test = this.http.get('http://localhost:8080/v1/places/all')
    .subscribe((res: Response) => {
      this.places = res.json()
    });
}`

`<input class="form-control" placeholder="Bestemming" id="place" name="place" [ng4-auto-complete]="places" no-record-text="Geen resultaat gevonden">`

Output: 
> static list found empty

`{{ places }}` works, ` [ng4-auto-complete]="places"` doesn't.

I'm lost for words, and I've been stuck on this problem for over two hours and I can't figure it out. 

The data I'm trying to use AutoComplete on:
`[
    "Gouda",
    "Bodengraven",
    "Amsterdam"
]`

**Comment by hardeep-bit** [comment]
**static list found empty** will come in console when the list you have provided on component initialization  is empty. As i can see you are providing the list while hitting the API, then you have to use [Dynamic function](https://www.npmjs.com/package/ng4-auto-complete#set-dynamic-list--) to update the list. check this. Please let me know

**Comment by agiratech-venkat** [comment]
$(...).autocomplete is not a function
initDropdown auto.directive.js:237
    configureDirective auto.directive.js:128
    ngOnInit auto.directive.js:22
    Angular 5
    View_ListingComponent_0 ListingComponent.html:186
    Angular 24
    RxJS 5
    Angular 8

Got this error when I am tryng to use.
I also added 
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
in my index.html

Can you please check why its been not loading
